### ISSUE TITLE
Message View, Sort Order and date

### ISSUE THREAD

**Issue by 001101** [humhub/mail#104]
Hello,

i was trying to change the **sort order for the message entry view**, but had no luck, there are different query statements with DESC order attribute, but no one seem to work when I set them to ASC order.

It also making no sense for me that if I send a message **the name of myself is shown in messages list and not the recipient**.

I will try later again, but request this in hope it can be adjusted.

It would be awesome nice if there is a module setting page where you can adjust:
How messages will get displayed - ASC or DESC order
How much messages will get displayed (for performance and usability)

It would also be much better if the **Editor for new reply is ON TOP of the messages** and not below, this could  also be a setting.

Also I don't understand why only the date is shown on messages, but not the time.
In the database is on 'created_at' table also the time and I could not find any greping in code which just puts the date on message title.
This is also important for better usability.

Thanks in advice

**Comment by luisalvarad** [comment]
Wolaa

**Comment by 001101** [comment]
What is 'Wolaa'?

**Comment by flaugere** [comment]
I'm totally agree. Especially with the point :

> It also making no sense for me that if I send a message the name of myself is shown in messages list and not the recipient.

@001101 Did you start something about that ?
