### ISSUE TITLE
bug "mail header" with lot of users

### ISSUE THREAD

**Issue by verbre** [humhub/mail#157]
The message block disappears with a large number of guests. Cause: The "mail-conversation-header" does not handle its height and chases the underlying block. Provisional solution found: apply "heigth: 100px"

http://prntscr.com/ndf87x
http://prntscr.com/ndf9k6

**Comment by funkycram** [comment]
Same problem here. My solution is to add this less code :
```
#mail-conversation-root {
	>.panel {
		>.panel-heading {
			.pull-right {
				max-width: 50%; // if many recipients
			}
		}
		>.panel-body {
			clear: right; // if many recipients
		}
	}
}
```

**Comment by luke-** [comment]
There is also a PR in the HumHub core which should solve this problem by limiting the max. displayed users.

https://github.com/humhub/humhub/pull/3419
