### ISSUE TITLE
mail module sizing more flexible

### ISSUE THREAD

**Issue by zogith** [humhub/mail#161]
Hi,
Mentioning this as a nice to have, as it was mentioned by a user on my site and I agree - the size of the messages in the mail module seems limited to an arbitrarily small size, they seem to be restricted to a tiny size that you have to scroll through regardless of the size of your monitor, it seems a bit arbitrary.
I looked through the existing open issues and couldn't see anything relating before mentioning this.
thanks.

**Comment by Ace2213** [comment]
Have you tried using CSS @media tags to customize this in your theme?
