### ISSUE TITLE
Admin-messages via mail module to all space members

### ISSUE THREAD

**Issue by SocioHub-FID** [humhub/mail#168]
Hi :)

Our users who admin a space asked for a functionality to send a message via the mail-module to all their space members. 

The motivation for this enhancement request is that (1) users rather read the email-notifications they receive from the mail module and (2) not all space admins are capable of using the function to set newsfeed-posts public/private for each post

We run www.sociohub-fid.de with HumHub - a portal for the social sciences which include a lot of research groups which use the space functionality.

HumHub: 1.3.13
Mail:  1.0.10

All the best,
David from the SocioHub team

**Comment by luke-** [comment]
I am not a fan of such a solution, because the message module is currently only intended for individual communication.

Probably it would make more sense for Space admins to be able to highlight important/individual posts, e.g. by e-mail or extra notification.

**Comment by sociohub-gesis** [comment]
Thanks for the quick response :)
