### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by helimansik** [humhub/mail#180]
to work on css. chat is hiding
![изображение](https://user-images.githubusercontent.com/68568040/88085697-6658ce00-cbb0-11ea-9354-a1467b94c594.png)

**Comment by Carl2213** [comment]
My workaround has been to hide the conversation list on viewports narrower than 1000px.

It's unnecessary since the chat list is accessible anyway through the persistent topbar.

**Comment by buddh4** [comment]
Did you try the new beta? The mobile view was enhanced.
