### ISSUE TITLE
Rename module as Messages

### ISSUE THREAD

**Issue by spoorun** [humhub/mail#185]
The name Mail implies email like functionality, which may be the case, but the Module is more similarly to a Messaging app, and with notifications is becoming more of a chat utility akin to Messenger or WhatsApp.

As such, and in particular if/when an email module is developed, the name 'Messages' would be more appropriate and understandable.

**Comment by Gilbertdelyon** [comment]
I agree 100%
Mail is a side functionnality of this module. It  will send mails only if you select it in the notification settings.

**Comment by luke-** [comment]
We will definitely change & correct this. Unfortunately, changing the module ID is difficult for existing installations.

**Comment by luke-** [comment]
Renamed to `Messenger` in v3.0+
