### ISSUE TITLE
Change profile send message button

### ISSUE THREAD

**Issue by buddh4** [humhub/mail#205]
Instead of 'Send message' use a mail icon button on user profiles. This will increase usability especially on mobile.

**Comment by ArchBlood** [comment]
@buddh4 so something like this?

### /mail/widgets/NewMessageButton.php
```php
    public function getLabel()
    {
        if($this->label !== null) {
            return $this->label;
        }

        return ($this->guid)
            ? Icon::get('envelope')
            : Icon::get('envelope-o');
    }
```
![Screenshot_2](https://user-images.githubusercontent.com/35392110/101970168-dff06780-3bf6-11eb-8b9a-a53f5e2c635e.png)

**Comment by buddh4** [comment]
Yes

**Comment by ArchBlood** [comment]
Only issues that I see is alignment in the dropdown is slightly off and the `+ Messages` still shows here
![Screenshot_3](https://user-images.githubusercontent.com/35392110/101991308-cb08e800-3c79-11eb-98bd-b11f88a67967.png)

**Comment by ArchBlood** [comment]
There, that should do it, although the alignment of the dropdown is still needed :smile:
