### ISSUE TITLE
Mail does not follow site theme, enforces own CSS

### ISSUE THREAD

**Issue by DiscordiaChaos** [humhub/mail#218]
I use a "dark" theme on my HumHub install. This makes the text very light-colored, close to white. The Mail module also has a very light message background by default, making the text impossible to read. Changing the theme to include the text boxes and background in Mail doesn't seem to work, the Mail module CSS seems to be layered on top of the site-wide theme. I am forced to edit the Mail CSS every time there is an update in order for people to read their messages.

Here is a screenshot of what I see when I "Inspect Element" on the conversation message bubble. The above is what the mail module renders, and the one under it is what I have in my theme. As you can see, the module is overtaking my preferences.
![image](https://user-images.githubusercontent.com/6591554/109701999-abd77380-7b61-11eb-9000-b508236ce0e6.png)

Preferably, Mail CSS would not overwrite the site-wide theme and would obey whatever I have set in there by default.

This seems related to #32

**Comment by buddh4** [comment]
As described in https://github.com/humhub/humhub/issues/4938 using css variables would solve those issues, I think this is a prime candidate for HumHub 1.9. You may could add `!important` rules to your theme, which is far from ideal, but I think currently the only way of overwriting this at the moment.

**Comment by DiscordiaChaos** [comment]
Thank you so much, that worked perfectly. :) No more having to update the module CSS every update!
