### ISSUE TITLE
Enable use of ALT + RETURN for new line, and RETURN to send messages 

### ISSUE THREAD

**Issue by Bexolo** [humhub/mail#223]
Would it be possible to allow the use of ALT + RETURN (cmd + return on mac) for new-lines, and RETURN to send messages in the messaging interface on desktop, please? 

Right now it is quite long and tiresome having to find and press the send button with the mouse each time.

**Comment by BaconTriple** [comment]
@Bexolo I assume you've not heard anything back on this or figured out a workaround?

**Comment by Bexolo** [comment]
> @Bexolo I assume you've not heard anything back on this or figured out a workaround?

I haven’t, no. I also stopped using the software due to the number of overall issues that my users encountered.
