### ISSUE TITLE
Message previews are not correctly encoding characters

### ISSUE THREAD

**Issue by Bexolo** [humhub/mail#224]
For example, if I send a message which contains "&", in the preview, it will appear as "&amp;". 

See screenshot below:
<img width="405" alt="Screenshot 2021-05-11 at 20 43 12" src="https://user-images.githubusercontent.com/31006885/117875184-c59be200-b299-11eb-8a3d-9e3871024116.png">

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/mail/pull/226

**Comment by luke-** [comment]
@yurabakhtin Thanks!
