### ISSUE TITLE
Images in Mail Notifcations

### ISSUE THREAD

**Issue by luke-** [humhub/mail#232]
Make sure embedded images are also supported by the mail module.
 
Core Issue: https://github.com/humhub/humhub/issues/4935

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/mail/pull/233 but only for `develop` 1.9 because master has no new class `RichTextToEmailHtmlConverter`:

<img width="657" alt="image_in_email" src="https://user-images.githubusercontent.com/6995524/120304475-7d8c4000-c2d8-11eb-9139-1f991eb5ec44.png">

**Comment by luke-** [comment]
@yurabakhtin Thanks!
