### ISSUE TITLE
Answer in left conversation: conversation doesn't show up, no notification

### ISSUE THREAD

**Issue by gerhardbeck** [humhub/mail#242]
There is a conversation I had with a user. I left the conversation some weeks ago.
Now he answered in the mail module
He thought it might reach me, but didn't reach me.

I'd expected it to reopen the left conversation and send me a notification, but that didn't happen.

**Comment by gerhardbeck** [comment]
I would more see it as a bug as my conversation partner sends me messages and I can't see them...

**Comment by nrgeen** [comment]
I can confirm the situation described. Unfortunately, it is not an exception. The person who remains alone in the room is not actively informed by the module that he is now alone. It would be desirable if every entry and exit of a fellow reader was briefly informed. This would also be helpful for message rooms with several people.

Therefore, I support the assessment that this is a bug.

**Comment by gerhardbeck** [comment]
Any development in this issue?

**Comment by gerhardbeck** [comment]
I have know the first persons, who wrote me but no notice showed up as the conversation was already deleted.

**Comment by luke-** [comment]
@gerhardbeck I'm trying to push the issue a bit.

**Comment by gerhardbeck** [comment]
@luke- thanks, that would be great. It's really a problem

**Comment by nrgeen** [comment]
Thanks a lot! 🥳

**Comment by gerhardbeck** [comment]
Thanks 👍
