### ISSUE TITLE
apostrophe not displayed correctly in conversations panel

### ISSUE THREAD

**Issue by funkycram** [humhub/mail#243]
### What steps will reproduce the problem?

Write this message:
`Test with ' apostrophe`

### What is the expected result?

In the left panel ("Conversations"), you should have `Test with ' apostrophe` (with the default `’` there is no bug)

### What do you get instead?

`Test with &#039; apostrophe`
![image](https://user-images.githubusercontent.com/23310825/144393993-e377fc9e-5430-44da-a02c-b8dbe4eb7ceb.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10.1
| Mail version   | 2.0.7

**Comment by yurabakhtin** [comment]
@luke- I cannot reproduce this:

<img width="1164" alt="mail" src="https://user-images.githubusercontent.com/6995524/144986754-afae3965-0183-4bc0-8ec2-6df2aa1dc7ce.png">

Similar issue but for another place was fixed here https://github.com/humhub/mail/issues/240 2 months ago.

**Comment by luke-** [comment]
@funkycram Can you please provide test data?

**Comment by funkycram** [comment]
This is what I have in my database which is  utf8mb4_unicode_ci:

![image](https://user-images.githubusercontent.com/23310825/145006017-d5698f54-2175-470e-95ae-7b90d21ff91f.png)

I have done another test with this sentence (when writing `and ' test "`, I had to to press the back space after the apostrophe and the quotation mark):
```
Test with ` apostrophe ‘ test “ and ' test "
```

Which is saved this way in the database:
```
Test with \` apostrophe ‘ test “ and ' test "
```

This is the result:

![image](https://user-images.githubusercontent.com/23310825/145006967-f3287b6d-ed07-4c73-8382-22126e6b6f51.png)

**Comment by yurabakhtin** [comment]
@funkycram @luke- Ah I found we already fixed this here https://github.com/humhub/mail/pull/226/files#diff-7bb062706140dff2a5dc470ba1f39413b19d16f9efc10a58844111d975964835R52 for wiki module version `2.0.8`.

**Comment by luke-** [comment]
@yurabakhtin Ah great, thanks!

**Comment by funkycram** [comment]
Great, thanks @yurabakhtin, works well on v2.10!
