### ISSUE TITLE
Edit message

### ISSUE THREAD

**Issue by orangiene** [humhub/mail#251]
![image](https://user-images.githubusercontent.com/62644500/150994740-19bde6f3-0aa3-4a84-8f61-7f5a0474000e.png)

![image](https://user-images.githubusercontent.com/62644500/150994767-b3d084f1-3123-47aa-b737-bd7ee06478c7.png)

**Comment by orangiene** [comment]
![Edit message #251](https://user-images.githubusercontent.com/62644500/150997431-0a1b2d2c-aebd-4ea5-b2ae-810e36fa19bd.jpg)
Edit message in 1000px width

![Edit message-full-screen](https://user-images.githubusercontent.com/62644500/150997440-3fb14707-e1d5-4945-97c9-b590e7383980.jpg)
Edit message full screen in 1140px width

**Comment by luke-** [comment]
@yurabakhtin It's already possible to edit messages. On Hover there is a pencil icon to open the edit modal. This issue is about to improve the UX of the Edit Dialog. Currently it's only 2 lines height.

Please a solution as simple as possible here.

**Comment by yurabakhtin** [comment]
@luke- @orangiene PR https://github.com/humhub/mail/pull/255:

Please review, I hope that is what required to do:

<img width="1157" alt="message1" src="https://user-images.githubusercontent.com/6995524/153804713-6589a55b-e870-427d-9d2f-e2da7713735a.png">

<img width="1178" alt="message2" src="https://user-images.githubusercontent.com/6995524/153804726-17fc2f17-14ab-437d-a352-2a0cff0d003b.png">

<img width="1169" alt="message3" src="https://user-images.githubusercontent.com/6995524/153804725-f411a385-9bbd-4959-be27-9b5811908690.png">

**Comment by orangiene** [comment]
@yurabakhtin if the modal has a width of 1000px, then it's fine.
I forgot the delete button in the screens, of course it is there. thank you.
