### ISSUE TITLE
Wrong user guid in LiveNotification 

### ISSUE THREAD

**Issue by aaukt** [humhub/mail#252]
The LiveNotification for a new message has the wrong user_guid set. It is always the guid of the sender when it should be the guid of the receiver. Since the guid is used to get the the new message count for the notification icons, this count is not the one of the receiver but the one from the sender.

There were changes here: https://github.com/humhub/mail/commit/e01dea5224ee2e80f4c71bcb55561fc467c09404#diff-0487b9fd961b3bf10933f32d88e670eeb708033584cc5c7ac56ce68c229825feR60

and here: https://github.com/humhub/mail/commit/de467042fac46bc4c4c3dc49cdc3fa9b59ddd753#diff-804ae173767e0e5bc98e3136ca3eb09055f050fb8d6c770fd9d6b7dd3972f01fR46

Could it be that this got mixed up?

I think in MessageNotification.php:73 it should still be `'user_guid' => $user->guid`.

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look here?

**Comment by yurabakhtin** [comment]
@aaukt I have tested and reviewed the code and for me it looks correctly.
Could you show us some screenshot with example where and what you expect to see instead of wrong data as you think?
Thanks.

**Comment by aaukt** [comment]
Login as two different users and send a message from the first one to the second one. Check the notification response the second user gets, it looks something like this:

```
{
    "type": "humhub.modules.mail.live.NewUserMessage",
    "contentContainerId": 1,
    "visibility": 2,
    "data": {
        "user_id": null,
        "user_guid": "787ad53c-b438-439f-a6e3-b6823b73f858",
        "message_id": 5,
        "count": "0"
    }
}
```

The user_guid is the one of the first user (sender). This same user_guid is used to fetch the "count" in the response here: https://github.com/humhub/mail/blob/master/live/NewUserMessage.php#L51
So the newMessageNotification for the recipient contains the count of new messages of the sender user, which is wrong.

Also just looking at the code again, the message_entry itself only has information about the sender, not the recipient (that connection is only made in message and user_message) so in any way here: https://github.com/humhub/mail/blob/master/models/MessageNotification.php#L73 it is always the sender user_guid that gets set for the notification. So i'm pretty sure it should be `'user_guid' => $user->guid` there, so that in the notification you actucally get your own new message count.

The count is used to show the new message count in the notification area. 
![image](https://user-images.githubusercontent.com/5297402/153204809-6934b0d1-7e9f-4bd1-b53a-f9404cb52839.png)
