### ISSUE TITLE
Mail to user-group

### ISSUE THREAD

**Issue by RoundAboutWEB** [humhub/mail#259]
It would be very helpful to be able to send to groups with the "Mail" module.
Currently, each recipient must be entered individually. However, it would be helpful if you can send to user groups.

![grafik](https://user-images.githubusercontent.com/26809494/163544734-c6260911-8a23-459e-bc95-ff3defeaa972.png)

**Comment by luke-** [comment]
@RoundAboutWEB The module is not designed for conversations with potentially so many participants.
