### ISSUE TITLE
Errors since upgrading to 1.12.0

### ISSUE THREAD

**Issue by crotalus258** [humhub/mail#268]
Errors being logged since upgrading to 1.12.0. It is currently the only error that’s being logged and I’m getting about 15 - 20 log entries a day. From what I can see it’s something to do with the mail module. I’ve already run the database integrity and rebuilt the search index, no help. 
<img width="926" alt="errors" src="https://user-images.githubusercontent.com/111092903/184249379-0ecd4419-d2ed-4d81-ac89-77576872208e.png">

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5845.

**Comment by luke-** [comment]
@yurabakhtin Thanks!

@crotalus258 Will be fixed with HumHub 1.12.1

**Comment by crotalus258** [comment]
@luke Thanks
