### ISSUE TITLE
How to disable ssl verify_peer verification in humhub emails?

### ISSUE THREAD

**Issue by Emerson-Gabriel** [humhub/mail#278]
Hello everyone, I'm getting the following response when trying to send a test email in my HumHub application:

Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.

According to my research I found that I need to add:

`'ssl' => [
                    'allow_self_signed' => true,
                    'verify_peer' => false,
                    'verify_peer_name' => false,
                ],`

In the mailer settings, however I don't know where to assign these settings if it's in the common.php file or somewhere else.

I don't have experience with Yii2 so I don't know how to solve the problem;

Can someone help me?

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/5893

**Comment by Emerson-Gabriel** [comment]
I'm using an aws server, it uses port 587, can you tell me an example of how the DNS would look?

Example:
smtp://USERNAME:PASSWORD@HOST:PORT?verify_peer=0
