### ISSUE TITLE
Wording of self-sent message preview

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#279]
Change "Dir" to "Du:"
![Bildschirmfoto 2023-01-24 um 11 17 50](https://user-images.githubusercontent.com/105652258/214266969-16ede590-4439-4fba-b418-134f44905e76.png)

**Comment by luke-** [comment]
@Semir1212 can you please fix this in the translation tool?

**Comment by Semir1212** [comment]
![image](https://user-images.githubusercontent.com/38326726/214329523-44d9d2f0-4265-4ef9-8d4d-2b935bf8665d.png)

Ist schon "Du" bzw. hat jmd seid dem letzten Update angepasst. @luke-

**Comment by luke-** [comment]
Stimmt, danke!
