### ISSUE TITLE
Color scheme of own messages

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#280]
Please color "own" messages with "primary" color 12% transparency (0.12)
![Bildschirmfoto 2023-01-24 um 13 28 35](https://user-images.githubusercontent.com/105652258/214291825-2524614b-f1a4-4f17-8bfd-159810837f35.png)

**Comment by spoorun** [comment]
This is good.
Though it is maybe a duplicate of: #219 !
(Use different colour bubble for each chat participant)

**Comment by yurabakhtin** [comment]
@Eladnarlea @luke- PR https://github.com/humhub/mail/pull/283:

![update-styles](https://user-images.githubusercontent.com/6995524/214541099-70212077-656b-41e2-bfd4-f23b3f465e19.png)
