### ISSUE TITLE
make the corner radius of every message the same.

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#281]
please make every corner rounded with a radius of 10px . even if more of the same persons messages follow along, every corner should still be 10px rounded.

![Bildschirmfoto 2023-01-24 um 16 39 26](https://user-images.githubusercontent.com/105652258/214338727-a98de7a8-d758-4d26-a5e2-c189e42db25f.png)

**Comment by yurabakhtin** [comment]
@Eladnarlea @luke- Fixed in the PR related to style update: https://github.com/humhub/mail/issues/280#issuecomment-1403402881.
