### ISSUE TITLE
New Design for Mail Module – To Do's

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#282]
![Bildschirmfoto 2023-01-24 um 16 46 59](https://user-images.githubusercontent.com/105652258/214341143-a40a61ea-2f6b-472f-a279-22d19748b972.png)

We have developed a new interface design for the Mail Module. You can find it in the figma files and I will comment and adress it to you.
Things that will change with the new look:
1. The "own" messages will be colored in the "primary" color of the certain network with a transparency of 12%. @luke- what if the primary color is black/white? 
2. When other User enter or leave a conversation, other attendees will be notified in the chat. The change will be displayed with the date and name that they left/entered the conversation. The style of this notifying message is different than the style of the conversation messages so that other attendees can see it is an informative message. It is designed like a white badge with semibold font-weight with a slight shaddow blur. please check figma for further detail. #285 
3. Messages that have been sent on the same day will be seperated with a "TODAY" badge (same style as other informative messages) for clearance and rough structuring. This can be developed further with other date declarations in the future. #286 
4. The name of the other person that one is writing to will be moved into the textfield itself instead of above. Style: Font-weight semibold. #287 .The profile picture of a person you're writing with within the group chat will move next to the start of the message. If it is a direct message, the name of the person you're writing to, is not necessary to be displayed all the time. it is enough to put the name of the person in the header and that's it. 
6. There will be an arrow down button when scrolling to the top of the messages. it will hover above the mail message input form. #289 
7. whenever someone edits a message, this specific message will be marked as edited in the right bottom corner. @luke- Proposal: we could also always display the time the message has been sent. #290
9. The Head of the Message will implement the same style as the new wiki module page entry header. Instead of the "created by.." the people who are also in the group chat will be displayed with their full name. Therefore the little profile preview bubbles will have to go. This makes the design look more coherent with the new wiki design, too.
Instead of the three dot menu in the right top corner, the design of the Wall entry editing possibilities will be implemented (check out the arrow down in the top right corner). The background color of the Message Head will be white with a separation line like in the new wiki module design.  #291
11. If the message is a direct message with another person, then only the persons name will be displayed in the chat header. (no need for a title or a subline with other message attendees.  #292 
13. The Group Chat will now have a picture you can upload for the group. #292

**Comment by Eladnarlea** [comment]
I will add screenshot examples tomorrow so don't worry :)

**Comment by spoorun** [comment]
It would be great to have the option to list conversations by sender, in the same manner of most modern messaging systems:  i.e. the conversation list is a list of contacts/groups with which a conversation is being had (rather than having multiple conversations with the same person).

**Comment by spoorun** [comment]
Whilst refreshing the mail module, it would also be very helpful to show different colour speech bubbles for each participant (or at least one colour for the account holder, and a different colour for those they are conversing with

**Comment by spoorun** [comment]
Will the new design enable a group conversation to have a 'Title' as well as the photo you have proposed (both would be really helpful)?

**Comment by spoorun** [comment]
Other things to consider perhaps;

- Rename the module to 'Messages' or 'Chat' Instead of Mail - mail seems really not so appropriate to the function the module has evolved to. #185 

- Reactions to messages (as most messaging clients have, i.e. add a thumbs up or heart to a message this adds a lot of efficiency, and reduces a chat become burdened with notifications and messages when people just want to add a simple reaction) #188
 
- Ability to quote messages in the reply and to forward messages #181 

- Typing notifications when a participant is currently typing in a conversation #213 

- Option to 'mute' a specific conversation, and so stop receiving notifications for that conversation (either until un-muted or for a fixed time?) #184
