### ISSUE TITLE
Date Badge "TODAY"

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#286]
Messages that have been sent on the same day will be seperated with a "TODAY" badge (same style as other informative messages but in UPPERCASE) for clearance and rough structuring. This can be developed further with other date declarations in the future.
![Bildschirmfoto 2023-01-25 um 11 43 57](https://user-images.githubusercontent.com/105652258/214545518-c72fb20e-b783-462f-892e-52f835e71d87.png)

**Comment by luke-** [comment]
@yurabakhtin Thanks
@Eladnarlea updated!

**Comment by Eladnarlea** [comment]
@yurabakhtin thank you! Done.
