### ISSUE TITLE
Move persons name into speech bubble in group chats!

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#287]
The name of the other person that one is writing to will be moved into the textfield itself instead of above. Style: Font-weight semibold.
![Bildschirmfoto 2023-01-25 um 11 43 57](https://user-images.githubusercontent.com/105652258/214546127-e9030ec3-1bfd-4cf3-9b9a-55f4fab866e2.png)

**Comment by yurabakhtin** [comment]
@Eladnarlea @luke- Commit https://github.com/humhub/mail/pull/283/commits/4a980604443797284e0525804aa78a08383dfc69:

![author-line](https://user-images.githubusercontent.com/6995524/214836436-a347d4f1-c8c2-4939-bc7a-b3d86e7f37aa.png)
