### ISSUE TITLE
Remove profile picture bubble and name in direct message

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#288]
When texting with only one person, please remove the name and profile picture next to every speechbubble. It is clear whom you're texting to therefore it's unnecessary information.

![Bildschirmfoto 2023-01-25 um 13 01 55](https://user-images.githubusercontent.com/105652258/214558347-a156a80b-6df8-4873-b2a5-cdb8bf6634be.png)

**Comment by yurabakhtin** [comment]
@Eladnarlea @luke- Commit https://github.com/humhub/mail/pull/283/commits/2682cbe32c180ad237bf0010f3a758044238e671.
