### ISSUE TITLE
Scroll Down Button

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#289]
There will be an arrow down button when scrolling to the top of the messages. it will hover above the mail message input form.

![Bildschirmfoto 2023-01-25 um 13 01 55](https://user-images.githubusercontent.com/105652258/214558700-7519d9af-dc8b-4db9-bd84-6452bde1b8b0.png)

**Comment by yurabakhtin** [comment]
@Eladnarlea @luke- Commit https://github.com/humhub/mail/pull/283/commits/17d58d5ecf0751164072db269768b5d65d093fc5:

![scroll-down-button](https://user-images.githubusercontent.com/6995524/214830971-c8d5d536-2a0a-4818-a278-adc840265f60.png)

**Comment by luke-** [comment]
@Eladnarlea is updated on your install

**Comment by Eladnarlea** [comment]
@luke- thanks
