### ISSUE TITLE
Message title, members and dropdown design

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#291]
The Head of the Message will implement the same style as the new wiki module page entry header. The background will be white with a border bottom: 1px solid #d7d7d7;

Instead of the "created by.." the people who are also in the group chat will be displayed with their full name. Therefore the little profile preview bubbles will have to go. This makes the design look more coherent with the new wiki design, too.

On top of that, the three dot menu drop down will be exchanged with the caret-down as known from the wall entry design and be placed in the top right corner of the message header.

Direct Message:

![Bildschirmfoto 2023-01-25 um 13 49 50](https://user-images.githubusercontent.com/105652258/214567784-1f1aecbb-7a98-434d-ae76-ce95f75c63dc.png)

Group Chat:

![Bildschirmfoto 2023-01-25 um 13 49 39](https://user-images.githubusercontent.com/105652258/214567789-fb013c68-1be0-4977-a138-2501a151485d.png)

Future Feature: live typing display 

![Bildschirmfoto 2023-01-25 um 13 50 00](https://user-images.githubusercontent.com/105652258/214567780-b2a578e2-d943-43c0-90f7-333716fdf6ce.png)

**Comment by yurabakhtin** [comment]
@Eladnarlea Commit https://github.com/humhub/mail/pull/283/commits/9bdbb07721d2eba783447ede5e6007bbb83b81f8:

![mail-header](https://user-images.githubusercontent.com/6995524/215096284-c9c5d47d-39cf-4229-adf2-b30c44ed39e0.png)

@luke- In previous version we displayed only single user name and text `+X others` like this:

![old-header](https://user-images.githubusercontent.com/6995524/215096976-6fff00ef-1839-4310-aab6-946dcfa71bc8.png)

Should we limit the new users list with some number?

---

> Future Feature: live typing display 
> ![Bildschirmfoto 2023-01-25 um 13 50 00](https://user-images.githubusercontent.com/105652258/214567780-b2a578e2-d943-43c0-90f7-333716fdf6ce.png)

Let me know when I shoould to start this.

**Comment by Eladnarlea** [comment]
> @Eladnarlea Commit [9bdbb07](https://github.com/humhub/mail/commit/9bdbb07721d2eba783447ede5e6007bbb83b81f8):
> 
@yurabakhtin could you take another look at the distances between the Title and User names and overall padding to the sides of the panel, please?

**Comment by yurabakhtin** [comment]
@Eladnarlea Ok, I have compared with figma version because the screenshots here are very small.
Commit https://github.com/humhub/mail/pull/283/commits/bc1480b939b138e5f49f9bfd22a48ae17811a786:

![mail-header](https://user-images.githubusercontent.com/6995524/215125482-b9fbd4a4-c6f3-4c0b-8a37-fab6ef9c95d0.png)

**Comment by Eladnarlea** [comment]
> Should we limit the new users list with some number?

@yurabakhtin yes please, at the moment it is not implemented but I think it is an important feature, especially when it comes to mobile view :)

**Comment by yurabakhtin** [comment]
@Eladnarlea Ok, commit https://github.com/humhub/mail/pull/283/commits/cb2d8a7628768f8e0fa22c82fba455db6acefef6:

![msg_limit_users](https://user-images.githubusercontent.com/6995524/216994394-0ee1d164-a2d9-4c81-beca-8b40141bacd0.png)

**Comment by Eladnarlea** [comment]
> @Eladnarlea Ok, commit [cb2d8a7](https://github.com/humhub/mail/commit/cb2d8a7628768f8e0fa22c82fba455db6acefef6):
> 
> ![msg_limit_users](https://user-images.githubusercontent.com/6995524/216994394-0ee1d164-a2d9-4c81-beca-8b40141bacd0.png)

can we limit the number of users related to the length of the panel? I think only two users in the chat list is too little if there is still so much space.

**Comment by yurabakhtin** [comment]
@luke- @Eladnarlea 

> can we limit the number of users related to the length of the panel?

I can try to detect a free space in the line by JS code on init page, but I think we will see a bit jumping the text, i.e. either we should display firstly all users and then they will be reduced by JS code, or we hide them all firstly and then display only some limited portion.

I.e. initally we will load all users from PHP side and then the list will be limited by JS code.
Also I am not sure it will works ideally because even from JS side we cannot know how much pixels are required for each char, e.g. if char `w` takes 8px, but `l` can takes 2px, so we can use some approximate value 5px for a char in order to know what totally chars can be inserted in the given width. And of course we should recalculate it on scale window width.

For me such complex JS calculation is not cost the result, so we might fill the line fo default window width and on small screen we might either reduce the line with `...` from CSS side or break to new line.
But even from PHP side we will use some approximate char pixel size, and of course we should calculate it on PHP side before print, because user names may have very different lengths.

**Comment by luke-** [comment]
@yurabakhtin Can we somehow work with the view size here? 
e.g. on small displays max. 2 users and for larger sizes max. 4

e.g.
```
User A, User B <span class="min-view-port-lg">, User C, User D</span>
```

**Comment by yurabakhtin** [comment]
@luke- 

> Can we somehow work with the view size here? e.g. on small displays max. 2 users and for larger sizes max. 4
> 
> e.g.
> 
> ```
> User A, User B <span class="min-view-port-lg">, User C, User D</span>
> ```

Yes, it would be easier to implement this if we need only to switch between 2 static numbers as you suggested, but please note in some cases the line may be broken to 2 lines when some user first and lat names are very long.
Please confirm to do this.

**Comment by luke-** [comment]
@Eladnarlea I can live with that. You too? :-)

**Comment by Eladnarlea** [comment]
I think this is one way to implement this. Another way would be to cut the names with dots that simbolise that there are more than only the ones that you see. 
(this would be an implementation as we did it in the wiki module index panel)
<img width="476" alt="Screen Shot 2023-03-01 at 9 52 28 AM" src="https://user-images.githubusercontent.com/105652258/222091165-38bead3f-954d-44bc-b8d5-044eb6978e14.png">

Whatsapp does that, too. We should agree if we think that it is important to display the number of members that are in this group chat. 

<img width="131" alt="Screen Shot 2023-03-01 at 9 58 47 AM" src="https://user-images.githubusercontent.com/105652258/222092497-b8458905-c384-4c41-b25a-e17f17d52677.png">

**Comment by luke-** [comment]
@Eladnarlea But in our case this could result in . e.g. `Max Huber, Kai Meier, and 24 o...`.

**Comment by Eladnarlea** [comment]
if we did it the way that whatsapp does it, we would not display "and 24 others". only the names of the persons would end dotted i.eg. `Max Huber, Kai Maier, Sabine Schultze Harald Schm...`

**Comment by luke-** [comment]
@Eladnarlea Ok understand. I would prefer to see a count of all participants.

**Comment by Eladnarlea** [comment]
all right well then we will do it @yurabakhtin 's way :)

**Comment by yurabakhtin** [comment]
@luke- @Eladnarlea Done in commit https://github.com/humhub/mail/pull/283/commits/c436f5ed51a82d79c9827b5485eb7d7468bfd928:

![user_count](https://user-images.githubusercontent.com/6995524/222894844-5b07a061-fd73-4e20-b7ea-fa2a1bb415dc.png)

![user_count_html](https://user-images.githubusercontent.com/6995524/222894848-0f56cd4a-fb62-4e99-8db3-421bbc15beae.png)
