### ISSUE TITLE
when click on "show all messages" link to current opened message instead of overview of messages

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#298]
https://user-images.githubusercontent.com/105652258/216976024-57812f2c-decc-441d-8936-42ac85358898.mov

**Comment by luke-** [comment]
@yurabakhtin Do you see a way that we can separate the SidebySide view into two views for small view ports.

- View without active message id (show only mail index)
- With Message Id (show mail only with back button to mail index)

**Comment by yurabakhtin** [comment]
@luke- I have done to expand the messages list on small screen if "Snow all messages" is loaded, otherwise the list is folded.
Commit https://github.com/humhub/mail/pull/283/commits/5aaa93e57559f287039b9c8747531bc7660e35ed.
