### ISSUE TITLE
Remove useless column `message_entry:file_id`

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/mail#299]
@luke- I detected the column `message_entry:file_id` is not used by the mail module.

Files are attached to a message entry without this column well, there `humhub\modules\file\components\FileManager` is used, so all linked files are stored in the core table `file`.

I suggest to remove the column `message_entry:file_id` and a related code completely. Do you agree?
Thanks.

**Comment by luke-** [comment]
@yurabakhtin Yes thanks, please delete this column and code!

**Comment by yurabakhtin** [comment]
@luke- I have done this in commit https://github.com/humhub/mail/pull/283/commits/c0677b76c1b9579adaad6bbc9135c02599d8b8aa of the existing PR https://github.com/humhub/mail/pull/283 in order to avoid conflicts on merging because we have there many changes in a related code and also this column removing is a not bugfix, so it can wait next release.
