### ISSUE TITLE
Conversation Panel Design

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#301]
@luke- Should we adapt the new styling of the Conversation Panel in order to complete the new look & feel of the Mail Module redesign? it is just small changes of the header, like "filter" should look the same like on the dashboard and the header of the Conversation Panel could look alike the new design of the wiki module? :) 

<img width="623" alt="Screen Shot 2023-02-20 at 9 08 14 AM" src="https://user-images.githubusercontent.com/105652258/220050071-1e8c08af-ddec-4ca1-aedd-ed6cc64fc947.png">

**Comment by Eladnarlea** [comment]
example of how the wiki panel design looks like in the header section

<img width="570" alt="Screen Shot 2023-02-20 at 9 24 28 AM" src="https://user-images.githubusercontent.com/105652258/220051659-2f0e3692-06a2-4a39-a1fd-71dd7ed1af9e.png">

**Comment by luke-** [comment]
@Eladnarlea Yes, lets do this!

**Comment by yurabakhtin** [comment]
@Eladnarlea @luke- Commit https://github.com/humhub/mail/pull/283/commits/e7758efeae44f059e0d782194f583df6c74c5117:

![mail-header](https://user-images.githubusercontent.com/6995524/221869132-3460bcf6-8cf6-485a-acf2-854b7e9aae91.png)

**Comment by Eladnarlea** [comment]
@yurabakhtin Please check again:

<img width="398" alt="Screen Shot 2023-03-01 at 10 51 01 AM" src="https://user-images.githubusercontent.com/105652258/222104991-3c874ae8-56c3-4243-bd50-99db5b8ae378.png">

1. Distance between "Conversations" and "filter"
2. Word "filters" doesn't look like on the dashboard "Filter" --> adapt the style of the dashboard, please
3. Title "Conversations" Strong (700). Please don't make it "strong" but make it 600.

**Comment by yurabakhtin** [comment]
@Eladnarlea @luke- Commit https://github.com/humhub/mail/pull/283/commits/3d8203c99270c13f19e858fe91f6a1db68d73650:

![msg-header](https://user-images.githubusercontent.com/6995524/222711041-e08b0e11-6819-484d-8023-5d10b9ea9f96.png)
