### ISSUE TITLE
Width of Message Panel should be the same as in Community Design

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#304]
At the moment the panel in enterprise responsive mode is very narrow. Please adjust it to the community edition.

How it should at least always be: _I think it is 780px width_
![Screen Shot 2023-02-28 at 9 48 21 AM](https://user-images.githubusercontent.com/105652258/221807114-661c86a5-5006-4d6c-a14e-2c54e56bb033.png)

too narrow:
![Screen Shot 2023-02-28 at 9 47 31 AM](https://user-images.githubusercontent.com/105652258/221807110-8ee2a552-25a3-4232-b6e3-657919ea2943.png)

too narrow:
![Screen Shot 2023-02-28 at 9 48 37 AM](https://user-images.githubusercontent.com/105652258/221807115-04b6e0fe-93e7-48bd-85de-7241c6a396b5.png)

This is how it looks like in the community edition:

![Screen Shot 2023-02-28 at 10 16 13 AM](https://user-images.githubusercontent.com/105652258/221808477-75fdb685-4c37-49e2-bfa0-92ccd62e6d8d.png)

![Screen Shot 2023-02-28 at 10 15 52 AM](https://user-images.githubusercontent.com/105652258/221808597-4a4ec05f-1f9f-4bbd-bb31-695c6d3e2bfc.png)

![Screen Shot 2023-02-28 at 10 15 38 AM](https://user-images.githubusercontent.com/105652258/221808592-5415c5e7-b9f2-4081-a69f-ec779725574f.png)

**Comment by yurabakhtin** [comment]
@Eladnarlea @luke- Done in commit https://github.com/humhub/mail/pull/283/commits/3d1944c29395542d92210423f853425379a53c0b.

**Comment by luke-** [comment]
@Eladnarlea Updated
