### ISSUE TITLE
When new conversation is started, unnecessary notification badges

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#305]
When a new conversation has started, only the date should be displayed as a notification badge. When new members enter the conversation after it has been created, only then there will be a notification badge that says "person xy joined the conversation" 
When members are part of the conversation from the very beginning, no extra notification should be displayed. 

<img width="761" alt="Screen Shot 2023-03-01 at 10 12 50 AM" src="https://user-images.githubusercontent.com/105652258/222095503-41b8e29c-ea52-44e7-a12a-c5ada08f275d.png">

**Comment by yurabakhtin** [comment]
@Eladnarlea @luke- Fixed in commit https://github.com/humhub/mail/pull/283/commits/91f72efab478b16e3c00eda31246c36d31671781.
