### ISSUE TITLE
"TODAY" Badge appears after every message sent, disappears when message is viewed the second time.

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#306]
https://user-images.githubusercontent.com/105652258/222124904-94b3ee65-0392-4a6b-9bd0-d4be93bb21a3.mov

**Comment by yurabakhtin** [comment]
@Eladnarlea @luke- Fixed in commit https://github.com/humhub/mail/pull/283/commits/91f72efab478b16e3c00eda31246c36d31671781.

**Comment by Eladnarlea** [comment]
It works that there is no more Today badge for every message but now we have another problem: 
The Today badge only appears when you leave the conversation and come back. It should be there immediately, though.

https://user-images.githubusercontent.com/105652258/222206170-7e9a8d4f-ee7e-46db-9ce2-0b3a1731b421.mov

**Comment by yurabakhtin** [comment]
@Eladnarlea Fixed in commit https://github.com/humhub/mail/pull/283/commits/169702ca4a48ceceaea673949c94786a9c002bba
