### ISSUE TITLE
Requesting for "Bengali language" Support

### ISSUE THREAD

**Issue by ishtiaque-2781** [humhub/mail#316]
![bengalisupport](https://user-images.githubusercontent.com/71713514/226620371-27f1180c-d85f-4bfd-ab8c-70a9b18b64b8.JPG)

**
While typing any message in Bengali, it shows only question marks in place of Bengali text. [screenshot attached]

Please, solve this issue. It will significantly help Bengali users.

Thanks.
**

**Comment by luke-** [comment]
Can you reproduce this on our Community site or demo hosting?

**Comment by luke-** [comment]
Make sure your database has the correct collation:
https://docs.humhub.org/docs/admin/server-setup#create-database-schema

**Comment by ishtiaque-2781** [comment]
> Make sure your database has the correct collation: https://docs.humhub.org/docs/admin/server-setup#create-database-schema

**Just adding another point to clarify:** 
in my self-hosted Humhub website, Bengali text is working properly in every other place ( for example: in spaces, in posts, and in comments). It just not working properly in this specific module. Since I have installed this module directly from the admin settings of my website, I think there is an issue with this module. it's just my guess, maybe I am wrong.
