### ISSUE TITLE
Button Rewording from 'Save' to 'Add' or 'Add User'

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#317]
I think it would make more sense if the text of the button was 'Add User' or simply 'Add' instead of 'Save'.
@Semir1212 @luke- what do you think?

![Screen Shot 2023-03-21 at 3 00 57 PM](https://user-images.githubusercontent.com/105652258/226630113-ce71dd7c-6bd0-4152-8452-55a3d14a2ee5.png)

**Comment by Semir1212** [comment]
You are basically already adding the users with the user picker.

I would just shorten the headline to "Add participants" and change the buttons to Cancel / / Confirm.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/mail/pull/318:

![mail-wording](https://user-images.githubusercontent.com/6995524/226893448-3ff71c29-80a7-4729-8175-d74d9a327249.png)
