### ISSUE TITLE
Display who is currently online

### ISSUE THREAD

**Issue by marc-farre** [humhub/mail#325]
I need to add the possibility to display who is online, in the conversation and on the left panel of all conversations.
![image](https://user-images.githubusercontent.com/23310825/235528103-b2ccaf3d-ec01-4168-b2b5-bd183002a5e6.png)

It also could be when adding a new user to a conversation:
![image](https://user-images.githubusercontent.com/23310825/235528188-709a8f8c-61f5-4a75-8e84-d03a84d37c68.png)

@luke-  do you prefer a PR, or should I create new module (e.g. `messenger-advanced`) for that?
Thanks!

**Comment by luke-** [comment]
@funkycram We need to check what is possible here with the `user_session` table. Possibly also mark logged in & inactive users differently (orange).

Additionally, users/operators should have the possibility to hide the online status.

@Eladnarlea Can you take a look here regarding the UI?

**Comment by Eladnarlea** [comment]
I would suggest the following: 
1. display a `green dot` next to the person that is online
2. don't display it in group chat preview (to see who's online you have got to click on participants list view-> `green dot` and `(online)` signalise the online status)
3. for now we should integrate only the `green dot `and the `(online)` text instead of introducing several colors that display the different status options. 


<img width="907" alt="Screenshot 2023-05-03 at 8 43 03 AM" src="https://user-images.githubusercontent.com/105652258/235848570-f8889599-b048-47d1-84f5-efb46668f188.png">

<img width="695" alt="Screenshot 2023-05-03 at 8 56 15 AM" src="https://user-images.githubusercontent.com/105652258/235851023-29ff035b-bfe7-4efc-9953-0c797f679db1.png">

**Comment by funkycram** [comment]
Thanks @luke- and @Eladnarlea . I agree with your suggestions @Eladnarlea , thanks for the screenshots, it will help me!

So I think I need to a property in `humhub\modules\user\widgets\Image`, perhaps `public $showOnlineStatus = false`. Have you got a better idea @luke- ?

> We need to check what is possible here with the user_session table.

The session doesn't seem to be written in the DB.
If I'm logged in with user ID 1 and I do:
```
        $user = \humhub\modules\user\models\User::findOne(1);
        echo $user->getHttpSessions()->count();
```
I have 0.

I also tried `var_dump($session->readSession(1));` but it returns an empty string.

And in my DB, I only have one line with a value nether changing:
![image](https://user-images.githubusercontent.com/23310825/235870069-eaa2a51a-4df0-4e4a-a90e-40d9ed66d875.png)

On other Humhub instances, I can see many lines, so perhaps it's different depending some settings.

Anyway, I we have a JS calling `humhub\modules\live\controllers\PollController` every 20 seconds, only if the page is open in the browser.
Perhaps we could use this controller to update a cache? Something like:
```
Yii::$app->cache->set(self::CACHE_ONLINE_PREFIX . Yii::$app->user->id, true, 60); // Expires in 60 seconds
```

And then, we can know if a user is online with `Yii::$app->cache->get(self::CACHE_ONLINE_PREFIX . $userId)`.

What do you think about this idea?

**Comment by luke-** [comment]
@funkycram Sounds good!

- I like the feature `humhub\modules\user\widgets\Image::$showOnlineStatus`.
- Would be great to have the "is online" handling logic in an extra service class e.g. `humhub\modules\user\services\IsOnlineService`.   
- Lets start with the Cache idea. Should be no big deal to change this logic afterwards, if everything is bundled in the service.

**Comment by funkycram** [comment]
Thanks.
@luke- PR https://github.com/humhub/mail/pull/328

**Comment by funkycram** [comment]
@luke- Summary of this new feature:
- Required issue for core: https://github.com/humhub/humhub/issues/6295
- Required PR for core: https://github.com/humhub/humhub/pull/6297
- PR for mail module: https://github.com/humhub/mail/pull/328

**Comment by marc-farre** [comment]
@luke- Maybe we could merge this PR https://github.com/humhub/mail/pull/328 now that Humhub 1.15 beta has been released?

**Comment by luke-** [comment]
@marc-farre Just merged. Can you please check it? There were some conflicts during merge.

**Comment by marc-farre** [comment]
@luke- Thanks for the warning.

Fixed in the same PR https://github.com/humhub/mail/pull/350 as the one for https://github.com/humhub/mail/issues/324 to avoid new conflicts again for only a single change in the less file.

Commit: https://github.com/humhub/mail/pull/350/commits/3ed802c73c07c6c65f40936a8f70de50726357dc

**Comment by luke-** [comment]
@marc-farre Thank you. I'll release the module vor the v15 users.
