### ISSUE TITLE
Request: Chat functionality

### ISSUE THREAD

**Issue by leonbollerup** [humhub/mail#34]
Hi,

A frequent request from my users is a facebook kinda chat .. both person to person but also group chats.

**Comment by jakeyjdavis** [comment]
+1

**Comment by blackandcold** [comment]
+1
ajax + controller that uses the mail api?

**Comment by unixfox** [comment]
:+1:

**Comment by runonce86** [comment]
Anyone knows if the Enterprise Edition includes chat functionality?

**Comment by buddha87** [comment]
No, there is no realtime chat yet. The chat feature will be implemented after v1.3 with the implementation of a realtime communication.

**Comment by marc-farre** [comment]
Maybe we could use https://docs.humhub.org/docs/admin/push-updates/ to implement real-time chat.

**Comment by ilMagnifico** [comment]
Bumping this too.

**Comment by marc-farre** [comment]
Tested following this doc: https://docs.humhub.org/docs/admin/push-updates/ (I plan to update it: https://github.com/humhub/documentation/issues/145).

It works perfectly, new messages are displayed in real time.

@luke- I think we can close this issue
