### ISSUE TITLE
User can't send message if he doesn't belong to the admin group

### ISSUE THREAD

**Issue by JoaoSilva-JS** [humhub/mail#341]
Even users who have permission to send private messages cannot be sent if they do not belong to the administrator group.
The following error message appears: "You don't have enough permissions to start a conversation with João Silva !"

![img2](https://github.com/humhub/mail/assets/78453835/98d7a6da-0d54-4b79-86c5-ac3271f1c8ab)
![img1](https://github.com/humhub/mail/assets/78453835/92b49482-bdd6-40df-8161-e36873cee168)

**Comment by JoaoSilva-JS** [comment]
@

**Comment by felixhahnweilheim** [comment]
Are you sure the receiver allows private messages?

![Screenshot_20230801_194338_Chrome.jpg](https://github.com/humhub/mail/assets/84990763/c391c023-52af-4d43-b893-41620a651e6b)
