### ISSUE TITLE
Error trying to open the messages by one user (system administrator)

### ISSUE THREAD

**Issue by optitsolutions** [humhub/mail#345]
FEHLER  Thu, 10 Aug 2023 12:13:03 +0200 Error
Error: Call to a member function is() on null in /usr/local/www/apache24/data/domain.de/protected/modules/mail/widgets/InboxMessagePreview.php:160
Stack trace:
#0 /usr/local/www/apache24/data/domain.de/protected/modules/mail/widgets/InboxMessagePreview.php(104): humhub\modules\mail\widgets\InboxMessagePreview->isOwnLastEntry()
#1 /usr/local/www/apache24/data/domain.de/protected/modules/mail/widgets/InboxMessagePreview.php(34): humhub\modules\mail\widgets\InboxMessagePreview->getMessagePreview()
#2 /usr/local/www/apache24/noexec/domain.de/protected/humhub/components/Widget.php(63): humhub\modules\mail\widgets\InboxMessagePreview->run()
#3 /usr/local/www/apache24/data/domain.de/protected/modules/mail/widgets/views/inbox.php(19): humhub\components\Widget::widget(Array)
#4 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/View.php(347): require('/usr/local/www/...')
#5 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/usr/local/www/...', Array)
#6 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/usr/local/www/...', Array, Object(humhub\modules\mail\widgets\ConversationInbox))
#7 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/Widget.php(249): yii\base\View->render('inbox', Array, Object(humhub\modules\mail\widgets\ConversationInbox))
#8 /usr/local/www/apache24/data/domain.de/protected/modules/mail/widgets/ConversationInbox.php(58): yii\base\Widget->render('inbox', Array)
#9 /usr/local/www/apache24/noexec/domain.de/protected/humhub/components/Widget.php(63): humhub\modules\mail\widgets\ConversationInbox->run()
#10 /usr/local/www/apache24/data/domain.de/protected/modules/mail/views/mail/_conversation_sidebar.php(31): humhub\components\Widget::widget(Array)
#11 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/View.php(347): require('/usr/local/www/...')
#12 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/usr/local/www/...', Array)
#13 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/usr/local/www/...', Array, NULL)
#14 /usr/local/www/apache24/data/domain.de/protected/modules/mail/views/mail/index.php(16): yii\base\View->render('_conversation_s...')
#15 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/View.php(347): require('/usr/local/www/...')
#16 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/usr/local/www/...', Array)
#17 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/usr/local/www/...', Array, Object(humhub\modules\mail\controllers\MailController))
#18 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('index', Array, Object(humhub\modules\mail\controllers\MailController))
#19 /usr/local/www/apache24/data/domain.de/protected/modules/mail/controllers/MailController.php(62): yii\base\Controller->render('index', Array)
#20 [internal function]: humhub\modules\mail\controllers\MailController->actionIndex(NULL)
#21 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#23 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#24 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('mail/mail/index', Array)
#25 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#26 /usr/local/www/apache24/noexec/domain.de/index.php(25): yii\base\Application->run()
#27 {main}

**Comment by yurabakhtin** [comment]
@optitsolutions @luke- I don't find how it is possible but the error tells that last message entry has no User, probably the User was deleted but the message entry was not, it is strange because it should be deleted as we have such code here https://github.com/humhub/mail/blob/master/Events.php#L106-L108.
I think the tool `php yii integrity/run` https://docs.humhub.org/docs/admin/troubleshooting/#data-integrity may helps to fix a broken DB structure.

I have done this PR https://github.com/humhub/mail/pull/346 in order to avoid similar errors in future.

**Comment by luke-** [comment]
@yurabakhtin Thanks!

**Comment by optitsolutions** [comment]
ok, thank you. The last message isn't the problem. I know the last message and I can read it impersonating the (active) user. I think, it must be an older message, because we deleted some users a week ago.
I'll try the integrity tool and give you a feedback.
