### ISSUE TITLE
File dropdown not visible on mobile

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/mail#357]
In mobile the file attachment dropdown is not visible and not accesible.

Not sure if this is to be fixed here or in HumHub core.

![Screenshot_20231026_193830_Chrome.jpg](https://github.com/humhub/mail/assets/84990763/9f9afac6-ce9e-40c6-a3b7-84ab10616661)

**Comment by felixhahnweilheim** [comment]
You can move the topic to HumHub core (I don't seem to have the permission here).

The bug also appears in a space: When there are just a few posts, so you can scroll down to the lowest and add a comment to it.

Quick fix:
```
.dropdown-menu {
  bottom: 110%; //instead of top: 100%
}
```
This way the dropdown is always above the buttons and always visible.

**Comment by luke-** [comment]
@marc-farre Can you please take a look into this?

**Comment by marc-farre** [comment]
Thanks @felixhahnweilheim for reporting this problem.

@luke- @Eladnarlea what do you think about having a drop up (instead of a drop down) for file uploading everywhere in Humhub?

Messenger:
![image](https://github.com/humhub/mail/assets/23310825/e0a60d8f-c32b-49b0-bcda-52b9d1fda57e)

Comment:
![image](https://github.com/humhub/mail/assets/23310825/84ad7b20-2a51-41ed-b313-bf1d46329151)

@luke- if you agree with this idea, on Humhub 1.15.0-beta-3, I'll add a `dropup` CSS class in `FileHandlerButtonDropdown` when `count($this->handlers) !== 0`.

**Comment by Eladnarlea** [comment]
For mobile use I would refrain from using a dropdown option in general. I would like to suggest to use a new layer here, where everything else, that is not important, is greyed out. On top of that, this design is beneficial for adding more options in the future, too.

WhatsApp:
![Screenshot 2023-11-06 at 11 21 30 AM](https://github.com/humhub/mail/assets/105652258/fb5d7dc6-1ba1-4cf3-b5ef-db721498cf37)

HumHub Suggestion:
![Screenshot 2023-11-06 at 11 33 39 AM](https://github.com/humhub/mail/assets/105652258/37c1f3a4-940f-4ac0-a7de-166de14a3752)

**Comment by luke-** [comment]
@Eladnarlea Maybe some topic for the new button concept?

**Comment by marc-farre** [comment]
@Eladnarlea thanks, yes, this could be suggested in another issue, because currently this view is not available on Humhub (I need to use Bootstrap).

@luke- do you agree for a PR with dropup as described in [my previous comment](https://github.com/humhub/mail/issues/357#issuecomment-1783804231)?

**Comment by luke-** [comment]
@marc-farre Hmm, I don't like to switch to "dropup" everywhere. It would be good to switch dynamically to a `dropup` when it's outside of the viewport/end of page.

Something like this:
https://jsfiddle.net/3s2efe9u/
https://stackoverflow.com/questions/21232685/bootstrap-drop-down-menu-auto-dropup-according-to-screen-position

**Comment by marc-farre** [comment]
@luke- Thanks for the idea.

Done in PR https://github.com/humhub/humhub/pull/6645

This behavior is natively supported by Bootstrap 4+ (see https://getbootstrap.com/docs/4.0/components/dropdowns/).
So after migrating to this version, this JS code must be removed.
