### ISSUE TITLE
Notifications error for deleted users

### ISSUE THREAD

**Issue by marc-farre** [humhub/mail#358]
When a user of a conversation is deleted, I get the following error in the log:

```
Could not send notification e-mail to: deleted-3198. Error:foreach()
argument must be of type array|object, null given
in
/var/www/humhub/protected/modules/mail/models/MessageNotification.php:63
in
/var/www/humhub/protected/modules/mail/models/MessageNotification.php:44
in
/var/www/humhub/protected/modules/mail/models/MessageEntry.php:51

$_POST = [
'ReplyForm' => [
'message' => 'The message'
]
]

'REQUEST_URI' => '/mail/mail/reply?id=4699'
```

Perhaps, in `Message::getUsers()` ([here](https://github.com/humhub/mail/blob/master/models/Message.php#L144)) we could add:
```php
->where(['user.status' => User::STATUS_ENABLED])
```

But I'm not quite sure if it solves the bug, as the error is `foreach() argument must be of type array|object, null given`. I don't understand why. It seams to be in `MessageNotification::notifyAll()` ([here](https://github.com/humhub/mail/blob/master/models/MessageNotification.php#L43)) that `$this->message->users` is returning `null` instead of an array.
I've checked in the DB, and I have 5 active users for this conversion and 1 deleted user.

**Comment by yurabakhtin** [comment]
@luke- @marc-farre Fixed in PR https://github.com/humhub/mail/pull/359, the problem was in that a deleted user has `email === NULL` but the method `yii\symfonymailer\Message::setTo()` exptects `array` or `string`.

**Comment by marc-farre** [comment]
@yurabakhtin Thanks!
