### ISSUE TITLE
Misplaced Online dot

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/mail#369]
In conversation next to every message of a user who is currently online a green dot is shown.

I think it should be online shown with the profile picture (first message of the row).

Screenshot from community.humhub.com:

![Screenshot_20240107_120008_Chrome.jpg](https://github.com/humhub/mail/assets/84990763/53513ae0-8303-4b0f-8e36-3b8de852a7cf)

@marc-farre Maybe you can look into this.

**Comment by marc-farre** [comment]
@felixhahnweilheim Thanks!

@luke- PR https://github.com/humhub/mail/pull/375
