### ISSUE TITLE
Error: Trying to get property "profile" of non-object

### ISSUE THREAD

**Issue by optitsolutions** [humhub/mail#374]
Since the last Message module update some of our users have this problem, when they triy to open the message overview.
yii\base\ErrorException: Trying to get property 'profile' of non-object in /usr/local/www/apache24/data/domain.de/protected/modules/mail/widgets/InboxMessagePreview.php:74

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/mail/pull/376.

**Comment by optitsolutions** [comment]
with the new mail module version the error appears in the logs again. just inserted the if statement into the code again manually ;-)

**Comment by luke-** [comment]
@optitsolutions Can you please try to run the integrity checker? 
https://docs.humhub.org/docs/admin/troubleshooting#data-integrity
