### ISSUE TITLE
Create Provider for New Search

### ISSUE THREAD

**Issue by luke-** [humhub/mail#382]

**Comment by yurabakhtin** [comment]
@luke- I have started it in the PR https://github.com/humhub/mail/pull/386:

![mail-meta-search](https://github.com/humhub/mail/assets/6995524/e0611d1e-3420-4990-b32e-5ace0cc76501)

Should we implement also new controller and search drivers with indexing as we have for Content searching?

![mail-search](https://github.com/humhub/mail/assets/6995524/cd02580b-76aa-4fcb-a631-cda6b864e4e3)

**Comment by luke-** [comment]
@yurabakhtin Cool. Can't we just use this existing view?

![image](https://github.com/humhub/mail/assets/4736168/eecb86c2-43ea-46cc-b37a-6b000817070d)

**Comment by yurabakhtin** [comment]
@luke- 

> Can't we just use this existing view?

Ok, I will try to do it.
I just thought we should display in the Meta Search panel `MessageEntry` records, but the Messaging Filter returns `Message` records, so I will display `Message` records in the in the Meta Search panel as well, is it ok?

**Comment by yurabakhtin** [comment]
@luke- Also currently we load only last 50 message entries on the right part, so if a message entry is a very old then user should scroll up to find it where it was written, i.e. current message searching has no a direct link to a Message Entry. If it is ok then we can use the current searching, otherwise we should implement another with direct linking to a Message Entry. What do you think?

**Comment by yurabakhtin** [comment]
@luke- Please review how it looks after commit https://github.com/humhub/mail/pull/386/commits/143ad914ac58dfbc1348399daaca6886fa1568a4 where I have applied the same searching what is used for the existing filter:

![mail-search](https://github.com/humhub/mail/assets/6995524/0e63b02b-feb0-47fc-9b05-07cc8372fc0e)

**Comment by luke-** [comment]
> @luke-
> 
> > Can't we just use this existing view?
> 
> Ok, I will try to do it. I just thought we should display in the Meta Search panel `MessageEntry` records, but the Messaging Filter returns `Message` records, so I will display `Message` records in the in the Meta Search panel as well, is it ok?

@yurabakhtin 

I would prefer to continue to display "Message" records here and not the search results in the MessageEntries.
But that's the current implementation, isn't it?

I think the current PR  is ok in terms of functionality. Is it something to check/discuss?

**Comment by yurabakhtin** [comment]
@luke- 

> I would prefer to continue to display "Message" records here and not the search results in the MessageEntries.
But that's the current implementation, isn't it?

Yes, it works this way, search items are "Message" records.

> I think the current PR is ok in terms of functionality. Is it something to check/discuss?

I confirm, you can merge it.
