### ISSUE TITLE
Message notification sender can be wrong sometimes

### ISSUE THREAD

**Issue by marc-farre** [humhub/mail#389]
`MessageNotification::getEntrySender()` is used to get the sender of the notification: https://github.com/humhub/mail/blob/master/models/MessageNotification.php#L218C24-L218C38

But it gets the sender from the latest entry: https://github.com/humhub/mail/blob/master/models/MessageNotification.php#L39

If a user adds a participant to the conversation, but is not the creator of the last message entry, the sender is wrong.

**Comment by yurabakhtin** [comment]
@luke- @marc-farre Fixed in PR https://github.com/humhub/mail/pull/390:

![test-mail-join](https://github.com/humhub/mail/assets/6995524/a7151f84-ea8d-472b-b656-e240b8787c33)
