### ISSUE TITLE
After upgrade to version 1.6 a warning onMetaSearchWidgetInit in log.

### ISSUE THREAD

**Issue by aronbos** [humhub/mail#403]
Configuration at /humhub/protected/modules/mail has an invalid event configuration: class 'humhub\modules\mail\Events' does not have a method called 'onMetaSearchWidgetInit 

After upgrading the mail module to version 1.6 this message s logged. Humhub version 1.6.1

**Comment by marc-farre** [comment]
@aronbos That's weird, because you have Messenger module version 3.2.2, should have the `onMetaSearchWidgetInit` method in the `Events.php` file:
https://github.com/humhub/mail/blob/master/Events.php#L222

Can you check your `Events.php` file?
What version of the Messenger module have you got?

**Comment by aronbos** [comment]
Yes, this in the Events.php on line 222:
```
    public static function onMetaSearchWidgetInit($event)
    {
        if (Yii::$app->user->isGuest) {
            return;
        }

        /* @var MetaSearchWidget $widget */
        $widget = $event->sender;

        $widget->addProvider(SearchProvider::class);
    }
```
So I checked the caller: 'REQUEST_URI' => '/marketplace/update/install?moduleId=mail'

So the logic is that the **old** version did not have the onMetaSearchWidgetInit event?

**Comment by marc-farre** [comment]
Yes, this method has been added to the version 3.2.2 for the new search engine of HumHub 1.16.
