### ISSUE TITLE
JS `DOMSubtreeModified` event is deprecated and will be removed from Chrome very soon

### ISSUE THREAD

**Issue by marc-farre** [humhub/mail#421]
It is used in 3 locations of this module.

Announcement: https://developer.chrome.com/blog/mutation-events-deprecation

JS Error in Chrome browser:

> humhub-app.js?v=1726243065:1 [Deprecation] Listener added for a 'DOMSubtreeModified' mutation event. This event type is deprecated, and will be removed from this browser VERY soon. Usage of this event listener will cause performance issues today, and represents a large risk of imminent site breakage. Consider using MutationObserver instead. See https://chromestatus.com/feature/5083947249172480 for more information.

**Comment by luke-** [comment]
@gevorgmansuryan Thanks for the quick fix!
