### ISSUE TITLE
Request: mass mail

### ISSUE THREAD

**Issue by jimmy0699** [humhub/mail#43]
would be nice to add mass mail function, additional input/select to pick group you want to mail to.

**Comment by programguy** [comment]
+1

**Comment by wannabe21** [comment]
+1
PLUS add on admin side user roles who are allowed to do this

**Comment by MatthiasHertel** [comment]
+1

**Comment by Penguinexpert1** [comment]
Yes please! Also please allow mail to be sent to all users, just a certain usergroup, all users of a certain space or certain individuals.
Thanks!

**Comment by luke-** [comment]
This module is not intended for this purpose.
